### ISSUE TITLE
Timer indicator for time based game mode

### ISSUE THREAD

**Issue by Neketek** [arachnid42/Dissonance-2#14]
We need to create organically looking timer for time based game modes.  It should replace score counter to show that current game level is based not on score but on time.

**Comment by Dubbinary** [comment]
The most simple variant of time tracker to implement we thought it could be the time counter at the position of score counter and one or two rectangles with alfa channel which are reducing their size along side with decreasing a given amount of time.
1. ![image](https://user-images.githubusercontent.com/6703780/41989826-47ce0e60-7a49-11e8-90eb-e62dd8465001.png)
![image](https://user-images.githubusercontent.com/6703780/41989840-512285a4-7a49-11e8-86f0-ef4c84f42e50.png)

2. ![image](https://user-images.githubusercontent.com/6703780/41989850-5dda254a-7a49-11e8-83c7-784abb140e7e.png)
![image](https://user-images.githubusercontent.com/6703780/41989861-69b20fcc-7a49-11e8-958e-c507cb50af2e.png)

**Comment by Dubbinary** [comment]
The more complex variants with specific shapes, currently are under designing.

**Comment by Neketek** [comment]
I made timer based on the design posted here.
