### ISSUE TITLE
Creation of Main Menu UI

### ISSUE THREAD

**Issue by Dubbinary** [arachnid42/Dissonance-2#15]
To create Main Menu UI, I need design sketch of the following draft below.
![image.png](https://images.zenhubusercontent.com/59d381abb0222d5de47a135b/5cb43185-7913-4a39-9952-10787991a475)
@nepanime please provide for me design sketch and supporting materials(sprites, materials, etc.)

**Comment by nepanime** [comment]
![image.png](https://images.zenhubusercontent.com/5a92bc0a4b5806bc2bc846d2/7286217f-60bb-4b19-a3bd-79ca0e88ffbc)
Main menu design reference

**Comment by Dubbinary** [comment]
![image](https://user-images.githubusercontent.com/6703780/41990793-267083ee-7a4c-11e8-9a0e-4676a2529c54.png)
