### ISSUE TITLE
Creation of the Configurable Mode UI screen

### ISSUE THREAD

**Issue by Dubbinary** [arachnid42/Dissonance-2#19]
We need to design a screen where player could configure the play mode and apply other color themes.

**Comment by Neketek** [comment]
We'll start creating this screen after we create list of difficulty levels, because right now there is no clear evidence what we can allow to edit to not break the game.

**Comment by Neketek** [comment]
@Dubbinary @nepanime I'm still working on mockup for configurable mode screeen(s)

**Comment by Neketek** [comment]
So we need two screens
1. Configurable mode startup
2. Configurable mode configuration

First one is not hard to do at all, but second is special. First problem there is sliders for min max values which are normal experience at the desktop but they are offering very bad experience at the mobile.  Maybe we should try to create two button inputs which contain value at the middle and to change this value user should tap or hold buttons. 
Another problem is size of the configuration screen. To solve this problem each setting block title should be a button which will show/hide settings block. In this way user will view only those setting which he wants. Closest reference to this inputs is html spoilers.

**Comment by Neketek** [comment]
![startup.png](https://images.zenhubusercontent.com/59d2aaccb0222d5de479fbc2/775dd9e5-e2ff-450f-86a4-5fc764af6b89)
![sliders.png](https://images.zenhubusercontent.com/59d2aaccb0222d5de479fbc2/ca80b467-db0c-4b0b-a288-c293785b354c)
![spoiler.png](https://images.zenhubusercontent.com/59d2aaccb0222d5de479fbc2/d53c95ae-51e7-4754-88b0-1184f1e72945)
![configuration.png](https://images.zenhubusercontent.com/59d2aaccb0222d5de479fbc2/b2cb409a-96a5-4db9-8300-6119f64e0ba4)

**Comment by Neketek** [comment]
@Dubbinary @nepanime This is mockups for our configurable mode mechanics
1. Startup
2. Sliders
3. Spoiler
4. Configuration layout

**Comment by Neketek** [comment]
I'm going to tweak min max values in the sliders.

**Comment by Neketek** [comment]
@Dubbinary Save button should close the configurable menu.

**Comment by Neketek** [comment]
@Dubbinary  Also me and Lisa think that it's better to position revert and save buttons at the same panel as back button to not force user to scroll bottom.

**Comment by Neketek** [comment]
@Dubbinary Just duplicating the information from our yesterday chat in telegram. You need to add "Random" option to initial game mode selection.  Value of this option should be GameMode.None
