### ISSUE TITLE
Missed shape color in basket

### ISSUE THREAD

**Issue by Dubbinary** [arachnid42/Dissonance-2#31]
In the different levels randomly I've got situations when shape color on the game field had missed in the basket.
![image.png](https://images.zenhubusercontent.com/59d381abb0222d5de47a135b/fdfde9b6-92a8-4055-b991-9731e662176a)

**Comment by Neketek** [comment]
I need to rewrite color randomizer of shape basket to use coroutine and to wait until shape basket is not ready.
