### ISSUE TITLE
Color palette selection. 

### ISSUE THREAD

**Issue by Neketek** [arachnid42/Dissonance-2#6]
This palette should consist of :
* 4 colors for shapes and shape basket tiles.
* Background color
* Background Light color
* Heart bonus color
* Explosion bonus color
* Freeze bonus color
@nepanime You can provide these colors if you like in the list of hexadecimal color format.

**Comment by nepanime** [comment]
![drafts colors.jpg](https://images.zenhubusercontent.com/5a92bc0a4b5806bc2bc846d2/c30e43ab-9313-44b2-a3c8-b879a3b29073)

I've created a few drafts with different color schemas and some of the draft are contain a new concepts of elements positioning. Please choose variant which you wold like more and then I'll provide hexadecimial colors of that draft.

**Comment by Neketek** [comment]
@nepanime Ok, I will review them soon enough. By the way what is the font which you are using?

**Comment by nepanime** [comment]
@Neketek                        Myriad Pro, Regular

**Comment by Neketek** [comment]
@nepanime  Second looks pretty decent.  Could you please give me the background texture? Resolution in a 1024 x 1812 px. I also think that snowflake shape is not informative( I mean if I didn't know what it is I would not understand what it is), so it's better to leave it as is, at least for now. Also could you please create a variation of the second variant where bonus counters will be located at the top of the screen?

**Comment by Neketek** [comment]
@nepanime third, fourth and fifth look good to, but at first I want to play a little bit with a second variant and see how it looks on the phone screen.

**Comment by nepanime** [comment]
@Neketek                        ![variant 2-01.jpg](https://images.zenhubusercontent.com/5a92bc0a4b5806bc2bc846d2/296931ca-41b9-405f-a534-f200b3abd3c5)  - second variant

**Comment by Neketek** [comment]
@nepanime Don't forget about background texture

**Comment by nepanime** [comment]
@Neketek                        ![back-01.png](https://images.zenhubusercontent.com/5a92bc0a4b5806bc2bc846d2/8a0d71a8-3f40-4406-bb87-af81bb737ca2)    - background

**Comment by Neketek** [comment]
@nepanime Thanks

**Comment by Neketek** [comment]
@nepanime  I made system which gives an ability of simple design presets creation. 

There are several properties which we can customize freely: 
* 4 main colors
* Basket shape color
* Heart Bonus Color
* Explosion Bonus Color
* Background Texture
* Bonuses Background color
* Two gradients for explosion particles
* Snowflakes particles color
* Font color

Right now default preset is the last one u sent me. 
I suppose we need ' a little bit' more of them. So I need you to draw several other design presets.  For each preset I need two images:
 * General design preset reference as you made them before
* background texture, even if it's solid color, but if it's solid color you can simply use 1x1px image, other types of textures: gradients, images should have size around 2 mb.

**Comment by nepanime** [comment]
![image.png](https://images.zenhubusercontent.com/5a92bc0a4b5806bc2bc846d2/a5ffcbd9-e5f2-439f-8686-a1df5c6cadcd) logo
