### ISSUE TITLE
Purchase thank you panel

### ISSUE THREAD

**Issue by Neketek** [arachnid42/Dissonance-2#63]
We need to add panel which will contain thank you message after purchase. 
It is and overlay panel like rating screen. It should contain small text message, large tap to continue button, and maybe pretty background image. Design is up to you again.

**Comment by Neketek** [comment]
@Dubbinary We will add text later, but you could improvise :)

**Comment by Dubbinary** [comment]
We have Purchase thank you panel looks as on screenshot below.
Solely, we needed to improve text on this panel if needed.
![image](https://user-images.githubusercontent.com/6703780/43406504-05c2f94a-9425-11e8-9386-5ee8d535df62.png)
