### ISSUE TITLE
PT Localization

### ISSUE THREAD

**Issue by Neketek** [arachnid42/Dissonance-2#72]
Preparing and testing Portuguese localization

**Comment by Neketek** [comment]
Ok. Now we need the help of the Martha's relatives to translate our game to Portuguese. 
There are two options how we can accomplish this task. 
1. Create dev desktop build in which they can preview their localization because in the desktop build streaming assets localization files will be just raw jsons. 
2. Just send them our Russian, Ukrainian and English localizations and then help them by answering questions which they might have for us and hopefully we'll get good Portuguese localization. 

Plus we need translations for our play store text:
1. Store page translation
2. Store purchases descriptions and names translations

**Comment by Neketek** [comment]
@Dubbinary @nepanime Read the comment above

**Comment by Dubbinary** [comment]
I've created user friendly Google Docs file which will be easy to fill.
https://docs.google.com/document/d/1I1avEJBSnffU-aUGPVAjz64BFFH_ilJ5M4pvzpGtp_I/edit?usp=sharing
