### ISSUE TITLE
9:18 UI adaptation

### ISSUE THREAD

**Issue by Neketek** [arachnid42/Dissonance-2#93]
I will add toggle to camera aspect script which will allow disabling its functionality. You should disable aspect adjustment and then check all panels to be sure that they are looking good and not broken. I expect that all spacing problems can be easily fixed by changing anchors of the elements.

**Comment by Dubbinary** [comment]
- [x] Adapt main UI components for 9:18 aspect ratio
- [x] Adapt tutorial for 9:18 a.r.
- [x] Toggle UI background image for different aspect ratio
- [x] Add adapted for 9:18 background images for all themes we are have
